CV-224290 - Castle issue chess960
ChessCom/Chess-Game pull request #40
Opened 2021-11-03 13:07 UTC by jokic989

2021-11-03 13:09 UTC, marcosdsanchez commented
Please add a failing test that ensures that the bug is fixed.

2021-11-03 15:42 UTC, marcosdsanchez requested changes

2021-11-03 15:42 UTC, marcosdsanchez commented on Tests/ChessGameTest.php
> +        $this->game->setFeatureFlag(true);
The game was not created as a chess960 game, it's using the rules of a standard game.

2021-11-03 15:42 UTC, marcosdsanchez commented on src/Chess/Game/ChessGame.php
> +
This is not related to this open source library.

2021-11-05 19:10 UTC, jokic989 commented on Tests/ChessGameTest.php
> +        $this->game->setFeatureFlag(true);
You can see row below, when i put the FEN i add a flag for it being 960 game.

2021-11-05 19:10 UTC, jokic989 commented on Tests/ChessGameTest.php
> +        $this->game->resetGame('nbbnqrkr/pppppppp/8/8/8/8/PPPPPPPP/NBBNQRKR w HFhf - 0 1');
Also here testing that it is not working for non 960 game (missing boolean param) @marcosdsanchez

2021-11-11 20:07 UTC, marcosdsanchez commented on Tests/ChessGameTest.php
> +        $this->game->resetGame('nbbnqrkr/pppppppp/8/8/8/8/PPPPPPPP/NBBNQRKR w HFhf - 0 1');
When resetting a game you are not assigning it the flag that sets it to chess960. It's not enough to add an initial FEN. It'll use the rules of a standard chess game like this.

2021-11-17 17:14 UTC, jokic989 commented on Tests/ChessGameTest.php
> +        $this->game->resetGame('nbbnqrkr/pppppppp/8/8/8/8/PPPPPPPP/NBBNQRKR w HFhf - 0 1');
Yes, that is what i am testing. That it will NOT work when there is a normal game. Testing that change did not affected standard chess game.

2023-05-31 12:15 UTC, closed without merging